"use client";

import { Loader2, Mic, SendHorizonal, Volume2, VolumeX } from "lucide-react";
import { useEffect, useRef, useState, useTransition } from "react";

import {
  onboardingChatAction,
  type CollectedFields,
  type OnboardingChatMessage,
} from "@/app/onboarding/chat-actions";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useGroqVoice } from "@/lib/voice/use-groq-voice";
import { useSpeechOutput } from "@/lib/voice/use-speech-output";
import { cn } from "@/lib/utils";

/** Markdown markers read terribly aloud — flatten to plain speech. */
function toSpeakable(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/^[-*]\s+/gm, "")
    .replace(/^#+\s+/gm, "")
    .replace(/\n{2,}/g, ". ")
    .replace(/\n/g, " ");
}

/**
 * Fadi-led welcome as a REAL conversation: every turn is generated by the model,
 * which adapts to whatever the user says and tracks what it's gathered. Falls
 * back to the scripted welcome (via onProviderUnavailable) when the user has no
 * working AI provider, so a brand-new account is never trapped.
 */

const GREETING =
  "Hey — I'm Fadi, your honest career mentor. I'll get you set up in a couple of minutes, then I'll take it from there. To start: what should I call you?";

const FIELD_LABELS: Array<[keyof CollectedFields, string]> = [
  ["fullName", "name"],
  ["targetRole", "target"],
  ["locationPreference", "location"],
  ["experienceLevel", "level"],
  ["careerGoals", "goals"],
  ["resumeText", "CV"],
  ["linkedInProfile", "LinkedIn"],
];

export function FadiOnboardingAI({
  onUseForm,
  onProviderUnavailable,
}: {
  onUseForm?: () => void;
  onProviderUnavailable?: () => void;
}) {
  const [messages, setMessages] = useState<OnboardingChatMessage[]>([
    { role: "assistant", content: GREETING },
  ]);
  const [collected, setCollected] = useState<CollectedFields | null>(null);
  const [draft, setDraft] = useState("");
  const [pending, startTransition] = useTransition();
  const [finishing, setFinishing] = useState(false);
  const [voiceOn, setVoiceOn] = useState(true);
  // Voice capability is client-only — gate the controls until after mount so the
  // first client render matches the server (no hydration mismatch).
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Fadi's voice — male, natural (see useSpeechOutput); + hands-free mic input.
  const { speak, stop: stopSpeaking, isSupported: ttsSupported } = useSpeechOutput({ rate: 1.0 });
  const { state: micState, start: startListening, stop: stopListening } = useGroqVoice({
    onTranscript: (text) => setDraft((d) => (d ? `${d} ${text}` : text)),
  });
  const isListening = micState === "recording";
  const isTranscribing = micState === "transcribing";

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, pending]);

  // Speak each new Fadi line aloud while voice is on. Browsers gate speech on a
  // user gesture, so the greeting first speaks once the user toggles voice or
  // sends; every reply after that is spoken automatically.
  const lastSpoken = useRef(-1);
  useEffect(() => {
    if (!voiceOn || !ttsSupported || pending) return;
    let idx = -1;
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "assistant") {
        idx = i;
        break;
      }
    }
    if (idx > lastSpoken.current) {
      lastSpoken.current = idx;
      speak(toSpeakable(messages[idx].content));
    }
  }, [messages, pending, voiceOn, ttsSupported, speak]);

  function toggleVoice() {
    if (voiceOn) {
      stopSpeaking();
      setVoiceOn(false);
      return;
    }
    setVoiceOn(true);
    // Speak the latest line now — this click unlocks browser audio.
    for (let i = messages.length - 1; i >= 0; i--) {
      if (messages[i].role === "assistant") {
        lastSpoken.current = i;
        speak(toSpeakable(messages[i].content));
        break;
      }
    }
  }

  function toggleMic() {
    if (isListening || isTranscribing) {
      stopListening();
    } else {
      stopSpeaking(); // don't transcribe Fadi's own voice
      startListening();
    }
  }

  function send() {
    const text = draft.trim();
    if (!text || pending) return;
    const next: OnboardingChatMessage[] = [...messages, { role: "user", content: text }];
    setMessages(next);
    setDraft("");

    startTransition(async () => {
      const res = await onboardingChatAction(next);
      if (!res.ok) {
        if (res.error === "provider" && onProviderUnavailable) {
          onProviderUnavailable();
          return;
        }
        setMessages((m) => [
          ...m,
          { role: "assistant", content: "Something glitched on my end — try that once more?" },
        ]);
        return;
      }
      setCollected(res.collected);
      setMessages((m) => [...m, { role: "assistant", content: res.reply }]);
      if (res.done) {
        setFinishing(true);
        // Hard navigation for the one-time onboarding → OS handoff. A
        // router.push + router.refresh here raced (refresh cancelled the push)
        // and stranded users on "Setting things up…" even though the profile
        // was saved. A full load guarantees the OS shell renders with a fresh
        // session + profile.
        window.location.assign(res.redirectTo ?? "/dashboard");
      }
    });
  }

  const capturedCount = collected
    ? FIELD_LABELS.filter(([k]) => Boolean(collected[k] && String(collected[k]).trim())).length
    : 0;

  return (
    <div className="mx-auto flex h-[min(80vh,640px)] w-full max-w-2xl flex-col overflow-hidden rounded-3xl border border-border/60 bg-card/70 shadow-2xl backdrop-blur">
      {/* Header */}
      <div className="flex items-center gap-3 border-b border-border/50 px-5 py-3">
        <FadiOrb />
        <div className="flex-1">
          <p className="text-sm font-semibold tracking-tight">Fadi</p>
          <p className="text-xs text-muted-foreground">Setting up your Fadi · {capturedCount}/7 captured</p>
        </div>
        <div className="hidden items-center gap-1 sm:flex">
          {FIELD_LABELS.map(([k, label]) => (
            <span
              key={k}
              title={label}
              className={cn(
                "h-1.5 w-3 rounded-full transition-colors",
                collected && collected[k] && String(collected[k]).trim() ? "bg-primary" : "bg-muted",
              )}
            />
          ))}
        </div>
        {mounted && ttsSupported ? (
          <button
            type="button"
            onClick={toggleVoice}
            aria-pressed={voiceOn}
            title={voiceOn ? "Fadi's voice is on — tap to mute" : "Turn on Fadi's voice"}
            className={cn(
              "grid size-8 shrink-0 place-items-center rounded-full border transition-colors",
              voiceOn
                ? "border-primary/40 bg-primary/10 text-primary"
                : "border-border/60 text-muted-foreground hover:text-foreground",
            )}
          >
            {voiceOn ? (
              <Volume2 className="size-4" aria-hidden="true" />
            ) : (
              <VolumeX className="size-4" aria-hidden="true" />
            )}
          </button>
        ) : null}
      </div>

      {/* Transcript */}
      <div ref={scrollRef} className="flex-1 space-y-3 overflow-y-auto px-5 py-4">
        {messages.map((m, i) => (
          <div
            key={i}
            className={cn(
              "flex items-end gap-2 duration-300 animate-in fade-in slide-in-from-bottom-1",
              m.role === "user" ? "flex-row-reverse" : "",
            )}
          >
            {m.role === "assistant" ? <FadiOrb size="sm" /> : null}
            <div
              className={cn(
                "max-w-[80%] whitespace-pre-wrap rounded-2xl px-3.5 py-2 text-sm leading-relaxed",
                m.role === "assistant"
                  ? "rounded-bl-sm bg-muted/70"
                  : "rounded-br-sm bg-primary text-primary-foreground",
              )}
            >
              {m.content}
            </div>
          </div>
        ))}
        {pending ? (
          <div className="flex items-center gap-2">
            <FadiOrb size="sm" />
            <div className="flex gap-1 rounded-2xl rounded-bl-sm bg-muted/70 px-3 py-2.5">
              <Dot /> <Dot delay="150ms" /> <Dot delay="300ms" />
            </div>
          </div>
        ) : null}
      </div>

      {/* Input */}
      <div className="border-t border-border/50 px-4 py-3">
        <div className="flex items-end gap-2">
          <Textarea
            autoFocus
            rows={2}
            value={draft}
            disabled={finishing}
            placeholder={finishing ? "Setting things up…" : "Type your answer…"}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                send();
              }
            }}
            className="resize-none"
          />
          {mounted && micState !== "unsupported" ? (
            <Button
              type="button"
              size="icon"
              variant={isListening ? "default" : "outline"}
              onClick={toggleMic}
              disabled={finishing}
              aria-label={isListening ? "Stop recording" : "Answer with your voice"}
              title={isListening ? "Listening — tap to stop" : "Answer with your voice"}
            >
              {isTranscribing ? (
                <Loader2 className="size-4 animate-spin" aria-hidden="true" />
              ) : (
                <Mic className={cn("size-4", isListening && "animate-pulse")} aria-hidden="true" />
              )}
            </Button>
          ) : null}
          <Button size="icon" onClick={send} disabled={pending || finishing} aria-label="Send">
            {finishing ? (
              <Loader2 className="size-4 animate-spin" aria-hidden="true" />
            ) : (
              <SendHorizonal className="size-4" aria-hidden="true" />
            )}
          </Button>
        </div>
        <div className="mt-2 flex items-center justify-between text-[0.7rem] text-muted-foreground">
          <span>Enter to send · Shift+Enter for a new line</span>
          {onUseForm ? (
            <button type="button" onClick={onUseForm} className="hover:text-foreground hover:underline">
              Prefer a form?
            </button>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function Dot({ delay = "0ms" }: { delay?: string }) {
  return (
    <span
      className="size-1.5 animate-bounce rounded-full bg-muted-foreground/60"
      style={{ animationDelay: delay }}
    />
  );
}

function FadiOrb({ size = "md" }: { size?: "sm" | "md" }) {
  const dim = size === "sm" ? "size-6" : "size-9";
  const inner = size === "sm" ? "size-2" : "size-3.5";
  return (
    <span className={cn("relative grid shrink-0 place-items-center", dim)}>
      <span className="absolute inset-0 rounded-full bg-primary/20 blur-md" />
      <span className="relative grid size-full place-items-center rounded-full bg-gradient-to-br from-primary to-[oklch(0.66_0.22_285)] ring-2 ring-primary/20">
        <span className={cn("animate-pulse rounded-full bg-primary-foreground/90 [animation-duration:2.5s]", inner)} />
      </span>
    </span>
  );
}
