/**
 * A tiny GitHub REST client for portfolio publishing (ADR 0008).
 *
 * Deliberately plain `fetch`, not Octokit: the calls we need are a thin, testable
 * wrapper, and Octokit is weight we don't want in the bundle. `fetch` is injected so the
 * whole client is unit-testable without a network — the request construction (paths,
 * method, base64 body, auth header) is exactly what a token typo or a wrong path would
 * break, and that is pinnable purely.
 *
 * SECURITY: the token is never logged. Callers must not log the client, its requests, or
 * raw error bodies (which can echo request headers). Errors surface status + GitHub's
 * message only.
 */

export type FetchLike = (
  url: string,
  init?: {
    method?: string;
    headers?: Record<string, string>;
    body?: string;
  },
) => Promise<{
  ok: boolean;
  status: number;
  json: () => Promise<unknown>;
  text: () => Promise<string>;
}>;

export class GitHubError extends Error {
  constructor(
    public readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = "GitHubError";
  }
}

const API = "https://api.github.com";

/**
 * The Phase-B refresh workflow (ADR 0008). Committed to the repo on first publish when
 * auto-refresh is on. It re-pulls the server-rendered snapshot and commits it if changed,
 * triggered by: a daily cron (safety net), a `repository_dispatch` Fadi fires on every
 * edit, and manual dispatch.
 *
 * REACHABILITY: the runner curls `snapshotUrl`, so this only functions when Fadi is
 * hosted at a PUBLIC url. From a localhost Fadi the direct-push (Phase A) is the working
 * path; the workflow's fetch step would fail until Fadi is deployed. Documented, not hidden.
 */
/**
 * The GitHub Actions workflow that DEPLOYS the static site to Pages (ADR 0008).
 *
 * This is what makes "Source: GitHub Actions" repos actually deploy. Our snapshot is a
 * finished, self-contained index.html (the SDK inlines all CSS/animations — no external
 * assets), so the workflow just uploads the repo as a Pages artifact and deploys it —
 * there is no build step. Standard `actions/upload-pages-artifact` + `actions/deploy-pages`,
 * running as the workflow's own GITHUB_TOKEN (so the deploy needs no user PAT permission).
 *
 * Triggers on push to the site branch and manually. On a repo whose Pages source is
 * already "GitHub Actions" (e.g. a former Jekyll site), just committing this file makes
 * the site deploy again.
 */
export function buildPagesDeployWorkflow(branch: string): string {
  return `name: Deploy portfolio to GitHub Pages
# Generated by Fadi (ADR 0008). Deploys the static portfolio — no build step.
on:
  push:
    branches: ["${branch}"]
  workflow_dispatch: {}
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
`;
}

export function buildRefreshWorkflow(snapshotUrl: string): string {
  return `name: Refresh portfolio
# Generated by Fadi (ADR 0008). Pulls the latest portfolio snapshot and commits it.
on:
  schedule:
    - cron: "0 6 * * *"
  repository_dispatch:
    types: [fadi-portfolio-updated]
  workflow_dispatch: {}
permissions:
  contents: write
concurrency:
  group: refresh-portfolio
  cancel-in-progress: true
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch latest snapshot
        run: curl -fsSL "${snapshotUrl}" -o index.html
      - name: Commit if changed
        run: |
          if ! git diff --quiet -- index.html; then
            git config user.name "fadi-bot"
            git config user.email "fadi-bot@users.noreply.github.com"
            git add index.html
            git commit -m "chore: refresh portfolio snapshot"
            git push
          else
            echo "No changes."
          fi
`;
}

/** Base64 for file contents (the PUT /contents API wants base64). */
export function toBase64(text: string): string {
  return Buffer.from(text, "utf8").toString("base64");
}

/** GitHub project sites need a "/<repo>" base path; a user site ("<login>.github.io") is root. */
export function pagesBasePath(login: string, repo: string): string {
  return repo.toLowerCase() === `${login.toLowerCase()}.github.io` ? "" : `/${repo}`;
}

/** The public Pages URL. A user site ("<login>.github.io") serves at the root — its own
 *  name is NOT a path segment — so it must not be appended, or every link Fadi stores
 *  and shows would point one level too deep. Must agree with pagesBasePath(). */
export function pagesUrl(login: string, repo: string): string {
  const host = `${login.toLowerCase()}.github.io`;
  return repo.toLowerCase() === host ? `https://${host}/` : `https://${host}/${repo}/`;
}

export class GitHubClient {
  constructor(
    private readonly token: string,
    private readonly fetchImpl: FetchLike,
  ) {}

  private async request(
    method: string,
    path: string,
    body?: unknown,
  ): Promise<{ status: number; data: unknown }> {
    const res = await this.fetchImpl(`${API}${path}`, {
      method,
      headers: {
        authorization: `Bearer ${this.token}`,
        accept: "application/vnd.github+json",
        "x-github-api-version": "2022-11-28",
        "user-agent": "fadi-portfolio-publisher",
        ...(body !== undefined ? { "content-type": "application/json" } : {}),
      },
      ...(body !== undefined ? { body: JSON.stringify(body) } : {}),
    });
    // Parse defensively: some GitHub responses (204s) have no JSON body.
    let data: unknown = null;
    try {
      data = await res.json();
    } catch {
      data = null;
    }
    return { status: res.status, data };
  }

  private fail(status: number, data: unknown, fallback: string): never {
    const msg =
      (data && typeof data === "object" && "message" in data
        ? String((data as { message: unknown }).message)
        : "") || fallback;
    throw new GitHubError(status, msg);
  }

  /** The authenticated user — used to resolve the owner login for Pages URLs. */
  async getAuthenticatedLogin(): Promise<string> {
    const { status, data } = await this.request("GET", "/user");
    if (status !== 200 || !data || typeof data !== "object" || !("login" in data)) {
      this.fail(status, data, "Could not read your GitHub account — check the token.");
    }
    return String((data as { login: unknown }).login);
  }

  /**
   * The repos this token can actually reach, newest first. For a fine-grained token this
   * is exactly its selected set — so it doubles as "what can I publish to?", which is the
   * whole point of showing a picker instead of a blind name field.
   */
  async listRepos(): Promise<Array<{ name: string; fullName: string; private: boolean }>> {
    // Paginate. A single page caps at 100, and "the repo I wanted wasn't in the list" is
    // indistinguishable from "the token can't see it" — so walk until GitHub runs out.
    // Bounded at 10 pages so a pathological account can't stall the picker.
    const out: Array<{ name: string; fullName: string; private: boolean }> = [];
    for (let page = 1; page <= 10; page += 1) {
      const { status, data } = await this.request(
        "GET",
        `/user/repos?per_page=100&page=${page}&sort=updated&affiliation=owner`,
      );
      if (status !== 200 || !Array.isArray(data)) {
        this.fail(status, data, "Could not list your repositories.");
      }
      const rows = data as Array<Record<string, unknown>>;
      for (const r of rows) {
        if (typeof r.name !== "string") continue;
        out.push({
          name: String(r.name),
          fullName: String(r.full_name ?? r.name),
          private: r.private === true,
        });
      }
      if (rows.length < 100) break;
    }
    return out;
  }

  /**
   * Whether the repo exists AND this token can see it. Returns "exists" | "missing" |
   * "no_access": a fine-grained token not scoped to the repo gets 403/404, which is NOT
   * the same as "create it" — creating would fail too. Distinguishing these is what lets
   * the caller give an actionable message instead of a blind create attempt.
   */
  async repoStatus(owner: string, repo: string): Promise<"exists" | "missing" | "no_access"> {
    return (await this.resolveRepo(owner, repo)).status;
  }

  /**
   * repoStatus, plus THE NAME GITHUB ACTUALLY HAS FOR THIS REPO.
   *
   * Renaming a repository does not break the API: GitHub silently follows the old name to
   * the new repo, so every write Fadi makes still lands. What it does break is the Pages
   * URL — that follows the NEW name. Publish under the stale name and the export is built
   * for "/old" while the site is served at "/new": the HTML loads and all ~47 assets 404,
   * which is a completely unstyled page with no error anywhere to explain it.
   *
   * So the canonical name is read back from the response and used for the base path and
   * the Pages URL, instead of trusting what we had stored.
   */
  async resolveRepo(
    owner: string,
    repo: string,
  ): Promise<{ status: "exists" | "missing" | "no_access"; name: string; owner: string }> {
    const { status, data } = await this.request("GET", `/repos/${owner}/${repo}`);
    if (status === 200) {
      const body = (data ?? {}) as Record<string, unknown>;
      const ownerLogin = (body.owner as Record<string, unknown> | undefined)?.login;
      return {
        status: "exists",
        name: typeof body.name === "string" && body.name ? body.name : repo,
        owner: typeof ownerLogin === "string" && ownerLogin ? ownerLogin : owner,
      };
    }
    if (status === 404) return { status: "missing", name: repo, owner };
    if (status === 403) return { status: "no_access", name: repo, owner };
    this.fail(status, null, `Unexpected status ${status} checking the repository.`);
  }

  /**
   * The files at the repo root, so the caller can warn before overwriting an existing
   * site. Fadi's own scaffolding (index.html, .nojekyll) is NOT "someone else's content",
   * so it's reported separately from foreign files. A brand-new auto-init repo has only a
   * README, which also isn't a portfolio — surfaced so the warning stays honest.
   */
  async listRootFiles(
    owner: string,
    repo: string,
  ): Promise<{ files: string[]; hasIndex: boolean; foreign: string[] }> {
    const { status, data } = await this.request("GET", `/repos/${owner}/${repo}/contents/`);
    // 404 = empty repo (no commits yet); treat as no content.
    if (status === 404) return { files: [], hasIndex: false, foreign: [] };
    if (status !== 200 || !Array.isArray(data)) {
      this.fail(status, data, "Could not read the repository contents.");
    }
    const files = (data as Array<Record<string, unknown>>)
      .filter((e) => typeof e.name === "string")
      .map((e) => String(e.name));
    // What Fadi manages itself, plus the auto-init README, don't count as a foreign site.
    const ours = new Set(["index.html", ".nojekyll", ".github", "README.md", "readme.md"]);
    return {
      files,
      hasIndex: files.includes("index.html"),
      foreign: files.filter((f) => !ours.has(f)),
    };
  }

  /**
   * Create a public repo under the authenticated user, with an auto-init commit.
   * NOTE: fine-grained tokens frequently cannot create repos (needs account-level
   * permission); callers should surface that as guidance, not a raw 403.
   */
  async createRepo(repo: string): Promise<void> {
    const { status, data } = await this.request("POST", "/user/repos", {
      name: repo,
      private: false,
      auto_init: true, // gives the repo a default branch so Pages can attach
      description: "My portfolio, published from Fadi.",
    });
    if (status !== 201) this.fail(status, data, "Could not create the repository.");
  }

  /**
   * Create or update a file. GitHub's PUT /contents is an upsert but REQUIRES the current
   * blob sha when the path already exists, so we look it up first. Idempotent: publishing
   * twice updates in place instead of erroring.
   */
  async putFile(args: {
    owner: string;
    repo: string;
    path: string;
    content: string;
    message: string;
    branch?: string;
  }): Promise<void> {
    const base = `/repos/${args.owner}/${args.repo}/contents/${args.path}`;
    const existing = await this.request("GET", base);
    const sha =
      existing.status === 200 &&
      existing.data &&
      typeof existing.data === "object" &&
      "sha" in existing.data
        ? String((existing.data as { sha: unknown }).sha)
        : undefined;

    const { status, data } = await this.request("PUT", base, {
      message: args.message,
      content: toBase64(args.content),
      ...(sha ? { sha } : {}),
      ...(args.branch ? { branch: args.branch } : {}),
    });
    if (status !== 200 && status !== 201) this.fail(status, data, `Could not write ${args.path}.`);
  }

  /** The repo's default branch (main | master | …) — needed to target the ref for a replace. */
  async getDefaultBranch(owner: string, repo: string): Promise<string> {
    const { status, data } = await this.request("GET", `/repos/${owner}/${repo}`);
    if (status !== 200 || !data || typeof data !== "object") {
      this.fail(status, data, "Could not read the repository.");
    }
    const branch = (data as { default_branch?: unknown }).default_branch;
    return typeof branch === "string" && branch ? branch : "main";
  }

  /**
   * DESTRUCTIVE replace: make the branch contain ONLY `files`, removing everything else in
   * ONE commit (ADR 0008 "Replace" mode). Uses the Git Data API:
   *   ref HEAD → new tree (NO base_tree, so it's the whole content, not a merge) →
   *   commit (parent = HEAD, history preserved) → move the ref.
   *
   * All-or-nothing: the branch only moves on the final PATCH, so a mid-flight failure
   * leaves the old site exactly as it was. This is the safe way to do an unsafe thing —
   * and it is only ever reached behind an explicit user confirmation.
   */
  async replaceAllFiles(args: {
    owner: string;
    repo: string;
    branch: string;
    /**
     * `encoding: "base64"` for BINARY files (fonts, images). Binary read as utf-8 and put
     * inline corrupts the file — a static site's self-hosted .woff2 fonts break silently.
     * Binary entries are uploaded as base64 blobs first and referenced by sha.
     */
    files: Array<{ path: string; content: string; encoding?: "utf-8" | "base64" }>;
    message: string;
  }): Promise<void> {
    const { owner, repo, branch } = args;
    const refPath = `/repos/${owner}/${repo}/git/refs/heads/${branch}`;

    const ref = await this.request("GET", refPath);
    if (ref.status !== 200) this.fail(ref.status, ref.data, `Could not read branch ${branch}.`);
    const headSha = String((ref.data as { object?: { sha?: unknown } })?.object?.sha ?? "");
    if (!headSha) this.fail(ref.status, ref.data, "Could not resolve the branch head.");

    // Binary files → create a base64 blob and reference its sha. Text files → inline content.
    const treeEntries = await Promise.all(
      args.files.map(async (f) => {
        const entry = { path: f.path, mode: "100644" as const, type: "blob" as const };
        if (f.encoding === "base64") {
          const blob = await this.request("POST", `/repos/${owner}/${repo}/git/blobs`, {
            content: f.content,
            encoding: "base64",
          });
          if (blob.status !== 201) this.fail(blob.status, blob.data, `Could not upload ${f.path}.`);
          return { ...entry, sha: String((blob.data as { sha?: unknown }).sha ?? "") };
        }
        return { ...entry, content: f.content };
      }),
    );

    // A tree with no base_tree = exactly these files, nothing else.
    const tree = await this.request("POST", `/repos/${owner}/${repo}/git/trees`, {
      tree: treeEntries,
    });
    if (tree.status !== 201) this.fail(tree.status, tree.data, "Could not build the replacement tree.");
    const treeSha = String((tree.data as { sha?: unknown }).sha ?? "");

    const commit = await this.request("POST", `/repos/${owner}/${repo}/git/commits`, {
      message: args.message,
      tree: treeSha,
      parents: [headSha],
    });
    if (commit.status !== 201) this.fail(commit.status, commit.data, "Could not create the commit.");
    const commitSha = String((commit.data as { sha?: unknown }).sha ?? "");

    // The single mutation that makes it live. Nothing before this changed the repo.
    const move = await this.request("PATCH", refPath, { sha: commitSha, force: false });
    if (move.status !== 200) this.fail(move.status, move.data, "Could not update the branch.");
  }

  /**
   * Enable Pages on the default branch. Returns the Pages URL GitHub reports. If Pages is
   * already enabled, GitHub 409s — treated as success, not an error.
   */
  async enablePages(owner: string, repo: string, branch = "main"): Promise<void> {
    const { status, data } = await this.request("POST", `/repos/${owner}/${repo}/pages`, {
      source: { branch, path: "/" },
    });
    if (status === 201 || status === 204) return;
    if (status === 409) return; // already enabled
    this.fail(status, data, "Could not enable GitHub Pages.");
  }

  /** Current Pages config, or null if Pages isn't enabled. `buildType`: "legacy" = deploy
   *  from a branch, "workflow" = GitHub Actions. */
  async getPagesConfig(
    owner: string,
    repo: string,
  ): Promise<{ buildType: string; branch: string | null; path: string | null } | null> {
    const { status, data } = await this.request("GET", `/repos/${owner}/${repo}/pages`);
    if (status === 404) return null;
    if (status !== 200) this.fail(status, data, "Could not read the Pages configuration.");
    const d = data as { build_type?: string; source?: { branch?: string; path?: string } };
    return {
      buildType: d.build_type ?? "legacy",
      branch: d.source?.branch ?? null,
      path: d.source?.path ?? null,
    };
  }

  /**
   * Ensure Pages serves the STATIC site directly from `branch` root ("deploy from a
   * branch"), switching OFF a GitHub-Actions build if the repo was configured that way.
   *
   * WHY: a Fadi portfolio is a self-contained index.html — it needs no build step, so
   * branch-serving is the correct, workflow-free deploy. The old `enablePages` only
   * created Pages and treated "already enabled" (409) as done — so a repo whose Pages was
   * set to "GitHub Actions" (e.g. a former Jekyll site) stayed on that source, and after
   * Replace deleted its workflow the push never deployed. This reconfigures it.
   *
   * Returns whether it had to switch away from an Actions-based deploy, so the caller can
   * tell the user their old workflow is no longer needed.
   */
  async ensureBranchPages(
    owner: string,
    repo: string,
    branch = "main",
  ): Promise<{ reconfiguredFromWorkflow: boolean }> {
    const current = await this.getPagesConfig(owner, repo);

    if (!current) {
      const { status, data } = await this.request("POST", `/repos/${owner}/${repo}/pages`, {
        source: { branch, path: "/" },
      });
      if (status !== 201 && status !== 204) this.fail(status, data, "Could not enable GitHub Pages.");
      return { reconfiguredFromWorkflow: false };
    }

    const alreadyBranchServed =
      current.buildType === "legacy" && current.branch === branch && current.path === "/";
    if (alreadyBranchServed) return { reconfiguredFromWorkflow: false };

    // Switch to branch-serving — from a workflow build, or from a different branch/path.
    const { status, data } = await this.request("PUT", `/repos/${owner}/${repo}/pages`, {
      build_type: "legacy",
      source: { branch, path: "/" },
    });
    if (status !== 200 && status !== 204) {
      this.fail(status, data, "Could not switch GitHub Pages to serve from the branch.");
    }
    return { reconfiguredFromWorkflow: current.buildType === "workflow" };
  }

  /**
   * Ensure the Pages source is "GitHub Actions" (build_type: workflow), so the committed
   * deploy workflow is what publishes the site. Idempotent: a no-op when it's already set
   * that way (the common case for a repo that previously used an Actions/Jekyll deploy),
   * which means it needs NO extra PAT permission in that case — the committed workflow
   * does the deploy on its own GITHUB_TOKEN.
   *
   * Returns whether it had to change the source (so the caller can note it).
   */
  async ensureActionsPages(owner: string, repo: string): Promise<{ changed: boolean }> {
    const current = await this.getPagesConfig(owner, repo);
    if (current && current.buildType === "workflow") return { changed: false }; // already correct
    const method = current ? "PUT" : "POST";
    const { status, data } = await this.request(method, `/repos/${owner}/${repo}/pages`, {
      build_type: "workflow",
    });
    if (status !== 200 && status !== 201 && status !== 204) {
      this.fail(status, data, "Could not set the Pages source to GitHub Actions.");
    }
    return { changed: true };
  }

  /**
   * Fire a repository_dispatch — the Phase-B hook Fadi calls on every edit so the hosted
   * site's refresh workflow runs without a manual re-publish.
   */
  async dispatch(owner: string, repo: string, eventType: string): Promise<void> {
    const { status, data } = await this.request("POST", `/repos/${owner}/${repo}/dispatches`, {
      event_type: eventType,
    });
    if (status !== 204) this.fail(status, data, "Could not trigger the refresh workflow.");
  }
}
